biantris/koa-server

- src/index.js
> feat(koa-router): add koa-router

- .gitignore
See https://github.com/beatrizoliveiira/koa-server/issues/3
> feat(git-ignore): add git-ignore

- src/server.js
See https://github.com/beatrizoliveiira/koa-server/issues/11
> fix(server): fix server.js with koa

- package.json
- yarn.lock
See https://github.com/beatrizoliveiira/koa-server/issues/7
> feat(esbuild): added esbuild

- babel.config.js
- webpack.js
- webpack/ReloadServerPlugin.js
ref https://github.com/biantris/koa-server/issues/21
> feat(modules-export): add modules.export in files

- src/modules/event/EventModel.ts
related https://github.com/biantris/koa-server/pull/24#discussion_r848408099
> feat(i-event): add interface to EventModel

- src/app.ts
- src/database/database.ts
related https://github.com/biantris/koa-server/issues/25#issue-1201821371
> feat(database): add connect database

- src/app.ts
- src/database/database.ts
- src/server.js
- webpack.js
related https://github.com/biantris/koa-server/issues/25#issuecomment-1096713577
> feat(server): add server file and try catch to connect db

- src/server.ts
related https://github.com/biantris/koa-server/pull/29#discussion_r859179516
> feat(m-ts): move server js to ts

- src/modules/event/EventModel.ts
ref https://github.com/biantris/koa-server/issues/33
> feat(model): improve schema model

- src/loader/index.ts
- src/loader/loaderRegister.ts
- src/modules/event/EventLoader.ts
related https://github.com/biantris/koa-server/issues/33
> feat(loader): add loaders

- src/modules/node/typeRegister.ts
ref https://github.com/biantris/koa-server/issues/33
> add type register

- src/modules/event/EventType.ts
ref https://github.com/biantris/koa-server/issues/33
> feat(event-type): add eventType

- src/modules/event/EventFilterInputType.ts
ref https://github.com/biantris/koa-server/issues/33
> feat(filter): add filter to event

- jest.config.js
- package.json
- src/modules/event/__tests__/EventQueries.spec.ts
- test/babel-transformer.js
- test/clearDatabase.ts
- test/connectMongoose.ts
- test/counters.ts
- test/deepPartial.ts
- test/disconnectMongoose.ts
- test/environment/mongodb.js
- test/getOrCreate.ts
- test/index.ts
- test/sanitizeTestObject.ts
- test/setupTestFramework.js
- yarn.lock
ref https://github.com/biantris/koa-server/issues/8
> feat(config-test): add config to test with jest

- src/schema/MutationType.ts
- src/schema/QueryType.ts
- src/schema/schema.ts
> feat(type): more type

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/workflows/auto-merge.yml
- .github/workflows/test.yml
> feat(github): automatic updating dependencies

- graphql/schema.graphql
- src/modules/event/mutations/EventCreateMutation.ts
- src/modules/event/mutations/index.ts
ref https://github.com/biantris/koa-server/issues/9#issuecomment-1136717899
> feat(event-c): improve naming

- graphql/schema.graphql
- package.json
- src/app.ts
- src/modules/event/EventModel.ts
- src/modules/event/__tests__/EventQueries.spec.ts
- src/modules/event/__tests__/__snapshots__/EventQueries.spec.ts.snap
- src/modules/event/mutations/EventCreateMutation.ts
- yarn.lock
related https://github.com/biantris/koa-server/issues/8
> feat(event-test): fix event test

- src/modules/event/__tests__/EventNodeQueries.spec.ts
related https://github.com/biantris/koa-server/issues/8
> feat(event-test-node): add eventNodeQueries test

- src/__tests__/__snapshots__/app.spec.ts.snap
- src/__tests__/app.spec.ts
related https://github.com/biantris/koa-server/issues/8
> feat(app): add supertest to validate routes

- .env.example
- package.json
- src/config.ts
- src/database/database.ts
- src/server.ts
- src/shared/index.ts
- src/shared/server.config.ts
- yarn.lock
ref https://github.com/biantris/koa-server/issues/78
> feat(env): add env

- package.json
- scripts/createSeedEvent.ts
- src/database/database.ts
- src/server.ts
> feat(event-seed): add script to create events

- graphql/schema.graphql
- src/modules/event/mutations/EventCreateMutation.ts
- src/modules/event/mutations/__tests__/EventCreateMutation.spec.ts
- src/modules/event/mutations/__tests__/__snapshots__/EventCreateMutation.spec.ts.snap
related https://github.com/biantris/koa-server/issues/9
> feat(event-c-test): add test to EventCreateMutation

- src/modules/event/mutations/__tests__/EventDeleteMutation.spec.ts
related https://github.com/biantris/koa-server/pull/93
> fix(event-test-d): fix event delete test

- README.md
- graphql/schema.graphql
- src/modules/event/mutations/EventUpdateMutation.ts
- src/modules/event/mutations/__tests__/EventUpdateMutation.spec.ts
- src/modules/event/mutations/__tests__/__snapshots__/EventUpdateMutation.spec.ts.snap
- src/modules/event/mutations/index.ts
ref https://github.com/biantris/koa-server/issues/9
- see https://www.mongodb.com/docs/manual/crud/
- see https://www.mongodb.com/docs/manual/reference/method/db.collection.update/
> feat(event-u): add eventUpdateMutation

- src/__tests__/__snapshots__/app.spec.ts.snap
- src/modules/event/EventType.ts
- src/modules/event/__tests__/__snapshots__/EventQueries.spec.ts.snap
- src/modules/event/mutations/EventUpdateMutation.ts
- src/modules/event/mutations/__tests__/EventUpdateMutation.spec.ts
- src/modules/event/mutations/__tests__/__snapshots__/EventUpdateMutation.spec.ts.snap
related https://github.com/biantris/koa-server/pull/95
> feat(event-u-test): improve test

- .github/workflows/codecov.yml
- package.json
ref https://github.com/biantris/koa-server/issues/97
> feat(codecov): add codecov

- .github/workflows/coverage.yml
related https://github.com/biantris/koa-server/pull/98
> fix(coverage): fix setup codecov

- package.json
related https://github.com/biantris/koa-server/issues/74
> feat(build): fix build script

- vercel.json
ref https://vercel.com/docs/errors#errors/missing-public-directory
ref https://github.com/biantris/koa-server/issues/74
> feat(vercel): deploy server

- src/app.ts
> feat(r-get): add get router root

- .gitignore
- .netlify/edge-functions-import-map.json
- functions/serverless-http.js
- netlify.toml
- package.json
- src/functions/app.js
- src/functions/serverless-http.js
- src/server.ts
- webpack.js
- yarn.lock
ref https://github.com/biantris/koa-server/issues/115
> fix(function): fix lambda function

- codecov.yml
related https://github.com/biantris/koa-server/issues/129
> feat(coverage): add coverage with codecov

- package.json
ref https://github.com/biantris/koa-server/issues/199
> feat(r): remove remove unused dependencies
